name: Build Docker Images

on:
  workflow_dispatch:
    
 # push:
  #  branches:
   #   - master
#  release:
#    types: [published]
#  schedule:
#    - cron: "0 7 * * *"

jobs:
  images:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      actions: read
      id-token: read
      contents: read
    steps:
      - name: checkout sources
        uses: actions/checkout@v4

      - name: Set tag to latest
#        if: (github.event_name == 'push' && github.ref == 'refs/heads/master') || github.event_name == 'schedule'
        run: |
          echo "DOCKER_TAG=latest" >> $GITHUB_ENV

      - name: Check if DOCKER_TAG is set
        if: env.DOCKER_TAG == ''
        run: |
          echo DOCKER_TAG is not set!
          exit 1

#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx
        with:
          install: true

      - name: Login to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          push: true
          tags: ghcr.io/ngeorger/wpscan:${{ env.DOCKER_TAG }}
